default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "gerenciador_projetos_rails" } %>

test:
  <<: *default
  database: gerenciador_projetos_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "gerenciador_projetos_rails" } %>
